language: python
cache: pip
os:
  - linux
services:
  - redis-server
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test;'
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install pytest
  - pip install -r requirements.txt
script:
    - make test
